# Form implementation generated from reading ui file 'uis\ui\part_two.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_part_two(object):
    def setupUi(self, part_two):
        part_two.setObjectName("part_two")
        part_two.resize(900, 600)
        self.scrollArea = QtWidgets.QScrollArea(parent=part_two)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(130, 10, 671, 511))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 652, 637))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.exp_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exp_label.setFont(font)
        self.exp_label.setWordWrap(True)
        self.exp_label.setObjectName("exp_label")
        self.gridLayout.addWidget(self.exp_label, 6, 0, 4, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.scrollAreaWidgetContents)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup = QtWidgets.QButtonGroup(part_two)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_4)
        self.gridLayout.addWidget(self.radioButton_4, 3, 3, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.scrollAreaWidgetContents)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.gridLayout.addWidget(self.radioButton_2, 1, 3, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.scrollAreaWidgetContents)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.gridLayout.addWidget(self.radioButton_3, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 3, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(parent=self.scrollAreaWidgetContents)
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(part_two)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_7)
        self.gridLayout.addWidget(self.radioButton_7, 7, 3, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(parent=self.scrollAreaWidgetContents)
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup_2.addButton(self.radioButton_8)
        self.gridLayout.addWidget(self.radioButton_8, 8, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 3, 1, 1)
        self.goal_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.goal_label.setFont(font)
        self.goal_label.setWordWrap(True)
        self.goal_label.setObjectName("goal_label")
        self.gridLayout.addWidget(self.goal_label, 11, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(parent=self.scrollAreaWidgetContents)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup.addButton(self.radioButton_5)
        self.gridLayout.addWidget(self.radioButton_5, 4, 3, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(parent=self.scrollAreaWidgetContents)
        self.doubleSpinBox_2.setMinimum(10.0)
        self.doubleSpinBox_2.setSingleStep(0.5)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 11, 2, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(parent=self.scrollAreaWidgetContents)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup.addButton(self.radioButton)
        self.gridLayout.addWidget(self.radioButton, 0, 3, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.scrollAreaWidgetContents)
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(48, 16777215))
        self.doubleSpinBox.setMinimum(10.0)
        self.doubleSpinBox.setSingleStep(0.5)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 11, 3, 1, 1)
        self.name_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_label.setFont(font)
        self.name_label.setWordWrap(True)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 0, 5, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(parent=self.scrollAreaWidgetContents)
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup_2.addButton(self.radioButton_6)
        self.gridLayout.addWidget(self.radioButton_6, 6, 3, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(parent=self.scrollAreaWidgetContents)
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup_2.addButton(self.radioButton_9)
        self.gridLayout.addWidget(self.radioButton_9, 9, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.buttons_next = QtWidgets.QDialogButtonBox(parent=part_two)
        self.buttons_next.setGeometry(QtCore.QRect(720, 550, 161, 31))
        self.buttons_next.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Abort|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttons_next.setObjectName("buttons_next")

        self.retranslateUi(part_two)
        QtCore.QMetaObject.connectSlotsByName(part_two)

    def retranslateUi(self, part_two):
        _translate = QtCore.QCoreApplication.translate
        part_two.setWindowTitle(_translate("part_two", "Анкета, часть 2"))
        self.exp_label.setText(_translate("part_two", "Допустим безрисковая ставка составляет 10% и вы инвестируете на идеальном рынке, где доходность прямо пропорциональна риску. Какую из следующих опций вы будете считать и безопасной, и выгодной:"))
        self.radioButton_4.setText(_translate("part_two", "При достижении снижения на 30%\n"
"от цены приобретения"))
        self.radioButton_2.setText(_translate("part_two", "При достижении снижения на 70%\n"
"от цены приобретения"))
        self.radioButton_3.setText(_translate("part_two", "При достижении снижения на 50%\n"
"от цены приобретения"))
        self.radioButton_7.setText(_translate("part_two", "Актив со средней доходностью 20%,\n"
"которая зависит от рыночной цены\n"
"спекулятивного актива"))
        self.radioButton_8.setText(_translate("part_two", "Менее надежный актив, но со средней\n"
"доходностью 30%, которая зависит от\n"
"рыночной цены спекулятивного актива"))
        self.goal_label.setText(_translate("part_two", "Допустим безрисковая ставка составляет 10% и вы инвестируете на идеальном рынке, где доходность прямо пропорциональна риску. Средняя доходность по секторам составляет 20%. Укажите интервал доходностей секторов, которые вы готовы рассматривать"))
        self.radioButton_5.setText(_translate("part_two", "При достижении снижения на 10%\n"
"от цены приобретения"))
        self.radioButton.setText(_translate("part_two", "Никогда, даже если актив обесценится"))
        self.name_label.setText(_translate("part_two", "При каком уровне падения цены актива вы примете решение продать актив для избежания дальнейших потерь, вместо докупания актива?"))
        self.radioButton_6.setText(_translate("part_two", "Положить под безрисковую ставку 10%"))
        self.radioButton_9.setText(_translate("part_two", "Крайне спекулятивный актив со средней\n"
"доходностью 50%, без гарантий выплаты"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    part_two = QtWidgets.QWidget()
    ui = Ui_part_two()
    ui.setupUi(part_two)
    part_two.show()
    sys.exit(app.exec())
