# Form implementation generated from reading ui file 'uis\ui\part_one.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_part_one(object):
    def setupUi(self, part_one):
        part_one.setObjectName("part_one")
        part_one.resize(900, 600)
        self.scrollArea = QtWidgets.QScrollArea(parent=part_one)
        self.scrollArea.setGeometry(QtCore.QRect(130, 220, 661, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(10, 30, 641, 80))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.goal_label = QtWidgets.QLabel(parent=self.widget)
        self.goal_label.setObjectName("goal_label")
        self.gridLayout.addWidget(self.goal_label, 2, 0, 1, 1)
        self.name_label = QtWidgets.QLabel(parent=self.widget)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.exp_label = QtWidgets.QLabel(parent=self.widget)
        self.exp_label.setObjectName("exp_label")
        self.gridLayout.addWidget(self.exp_label, 1, 0, 1, 1)
        self.expBox = QtWidgets.QSpinBox(parent=self.widget)
        self.expBox.setObjectName("expBox")
        self.gridLayout.addWidget(self.expBox, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.goalBox = QtWidgets.QComboBox(parent=self.widget)
        self.goalBox.setObjectName("goalBox")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.gridLayout.addWidget(self.goalBox, 2, 1, 1, 2)
        self.nameBox = QtWidgets.QLineEdit(parent=self.widget)
        self.nameBox.setObjectName("nameBox")
        self.gridLayout.addWidget(self.nameBox, 0, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.buttons_next = QtWidgets.QDialogButtonBox(parent=part_one)
        self.buttons_next.setGeometry(QtCore.QRect(720, 550, 161, 31))
        self.buttons_next.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Abort|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttons_next.setObjectName("buttons_next")

        self.retranslateUi(part_one)
        QtCore.QMetaObject.connectSlotsByName(part_one)

    def retranslateUi(self, part_one):
        _translate = QtCore.QCoreApplication.translate
        part_one.setWindowTitle(_translate("part_one", "Анкета, часть 1"))
        self.goal_label.setText(_translate("part_one", "Какая ваша цель в инвестировании/торговле?"))
        self.name_label.setText(_translate("part_one", "Укажите ваше имя"))
        self.exp_label.setText(_translate("part_one", "Сколько лет вы занимаетесь инвестированием/торговлей?"))
        self.goalBox.setItemText(0, _translate("part_one", "Оптимизация портфеля и диверсификация"))
        self.goalBox.setItemText(1, _translate("part_one", "Быстрая спекулятивная торговля"))
        self.goalBox.setItemText(2, _translate("part_one", "Максимальный рост цены портфеля"))
        self.goalBox.setItemText(3, _translate("part_one", "Максимальный рост доходов с портфеля"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    part_one = QtWidgets.QWidget()
    ui = Ui_part_one()
    ui.setupUi(part_one)
    part_one.show()
    sys.exit(app.exec())
